[Rainmeter]
Update = 1000

[MetaData]
Author = Abyss03
Version 0.1
Name = Calender

[Variables]
fontName = Orbitron Medium
fontColour = 102,204,255, 200

;---------------------------------------------------
;------------------- Styles Below ------------------
;---------------------------------------------------

[styleTitle]
StringAlign = Center
StringCase = Upper
StringStyle = Bolditalic
StringEffect = Shadow
FontEffectColor = 0,0,0,50
FontColor = #fontColour#
FontFace = #fontName#
FontSize = 20
AntiAlias = 1
ClipString = 2

[styleText]
StringAlign = Left
StringCase = Upper
StringStyle = Bolditalic
StringEffect = Shadow
FontEffectColor = 0,0,0,50
FontColor = #fontColour#
FontFace = #fontName#
FontSize = 13
AntiAlias = 1
ClipString = 2

[styleData]
StringAlign = Right
StringCase = Upper
StringStyle = Bolditalic
StringEffect = Shadow
FontEffectColor = 0,0,0,50
BarColor = #fontColour#
FontColor = #fontColour#
FontFace = #fontName#
FontSize = 13
AntiAlias = 1
ClipString = 2